language: php
dist: focal

jobs:
  include:
    - os: linux
      dist: bionic
      php: 7.3
    - php: 7.4
    - php: 8.0snapshot
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

branches:
  only:
    - master
    - /^\d+\.\d+\.(?:\d+|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
