language: php
dist: xenial

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

branches:
  only:
    - master
    - /^\d+\.\d+\.(?:\d+|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - travis_retry sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
