language: php

matrix:
  include:
    - php: 5.6
    - php: 7
  fast_finish: true

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script: phpunit
