language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
  allow_failures:
    - php: 7.2
  fast_finish: true

branches:
  only:
    - master
    - /^v\d\.\d\.(?:\d{1,2}|x)/

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
