language: php

php:
  - 5.5
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit