language: php

matrix:
  include:
    - php: 5.5.9
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm
  fast_finish: true

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit