language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
  allow_failures:
    - php: 7.2
  fast_finish: true

branches:
  only:
    - master
    - /\d\.\d\.(?:\d{1,2}|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
