name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: pcov

      - name: Setup Composer
        id: setup-composer
        run: echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-composer.outputs.cache-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install -n --prefer-dist --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Send code coverage
        if: ${{ success() }}
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/log/clover.xml
