name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0']
    steps:
      - name: Checkout sources
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: pcov

      - name: Setup Composer
        id: setup-composer
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-composer.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update -n --prefer-dist --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Send code coverage
        if: ${{ success() }}
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/log/clover.xml
